### ISSUE TITLE
PDF417 return null value

### ISSUE THREAD

**Issue by esgantivar** [dealrinc/cordova-gmv-barcode-scanner#25]
Hi!

We try to develop a app that read pdf417 barcode (dni Colombia), sometimes plugin works well but a lot of dni return value of barcode null and crash the app

When use the example app generate's the same behavior.

Thanks!

**Comment by fseve** [comment]
Hola, lograste hacerlo funcionar para las cédulas de Colombia? Agradecería una ayuda

**Comment by esgantivar** [comment]
> Hola, lograste hacerlo funcionar para las cédulas de Colombia? Agradecería una ayuda

Hola, no terminamos usando este plugin, en general todos los plugin que intentamos usar para leer las cédulas de Colombia fallan de una u otra manera, la solución (en iOS) que finalmente encontramos fue modificar el codigo fuente del plugin para que retorne el rawValue de la lectura del pdf417 y crear una función para decodificar este valor crudo, desafortunadamente este desarrollo es privado y no puedo compartir la solución, pero esta es la idea general.

Como dato a tener en cuenta, las cédulas en Colombia tienen diferentes tipos de codificación, lo que hay que tener en cuenta al momento de crear la función encargada de decodificar los valores crudos.

Saludos!
