### ISSUE TITLE
IOS 13 camera display issue

### ISSUE THREAD

**Issue by CrescentLee** [dealrinc/cordova-gmv-barcode-scanner#33]
The new IOS 13 will cause a display issue for the usage of scanner. Below is my code and picture of display.
Cause IOS 13 introduces the new page layout, so the button position is dropped and can only see half shape. Is there any solution for this?
`    var options = {
        types: {
            QRCode: true
        },
        detectorSize: {
            width: .5,
            height: .3
        }
    }
    window.plugins.GMVBarcodeScanner.scan(options, function (err, result) {
        //Handle Errors
        if (err) return;
        //Do something with the data.
        if (result !== '') {
            // continue
            soundBeep();
            $('#putawayaction2_txtLocation').val(result);
        }
    });`
![Image from iOS](https://user-images.githubusercontent.com/41898572/89274687-d74dba80-d673-11ea-8037-bac9a3217ec3.png)

**Comment by f-cherchali** [comment]
Hello, 
I'm facing the same problem with iOS 15 with XS MAX, did you found any solution for that ?

**Comment by CrescentLee** [comment]
> Hello, I'm facing the same problem with iOS 15 with XS MAX, did you found any solution for that ?

Yes, this is due to IOS 13 new page modal features and you need to change cordova IOS source code
https://stackoverflow.com/questions/56435510/presenting-modal-in-ios-13-fullscreen
I forgot how I solved it, but this question might be helpful.
